import { DebtRecord } from './types';

export const DUMMY_DATA: DebtRecord[] = [
  {
    id: '1',
    name: 'Budi Santoso',
    amount: 500000,
    currency: 'IDR',
    type: 'hutang',
    status: 'belum lunas',
    date: '2024-05-01',
    dueDate: '2024-06-15',
    description: 'Pinjaman untuk modal usaha kecil',
  },
  {
    id: '2',
    name: 'PT. Sejahtera Abadi',
    amount: 2500000,
    currency: 'IDR',
    type: 'piutang',
    status: 'belum lunas',
    date: '2024-05-05',
    dueDate: '2024-07-01',
    description: 'Invoice #INV-2024-001',
  },
  {
    id: '3',
    name: 'Citra Lestari',
    amount: 150000,
    currency: 'IDR',
    type: 'piutang',
    status: 'lunas',
    date: '2024-04-20',
    dueDate: '2024-05-20',
    description: 'Pembayaran jasa desain logo',
  },
  {
    id: '4',
    name: 'Warung Makan Sederhana',
    amount: 75000,
    currency: 'IDR',
    type: 'hutang',
    status: 'lunas',
    date: '2024-05-10',
    dueDate: '2024-05-10',
    description: 'Makan siang tim',
  },
  {
    id: '5',
    name: 'Agus Wijaya',
    amount: 1200000,
    currency: 'IDR',
    type: 'hutang',
    status: 'belum lunas',
    date: '2024-05-12',
    dueDate: '2024-08-12',
    description: 'Uang muka pembelian motor',
  },
    {
    id: '6',
    name: 'Toko Buku Gramedia',
    amount: 350000,
    currency: 'IDR',
    type: 'hutang',
    status: 'belum lunas',
    date: '2024-05-20',
    dueDate: '2024-06-25',
    description: 'Pembelian buku referensi',
  },
  {
    id: '7',
    name: 'Siti Aminah',
    amount: 800000,
    currency: 'IDR',
    type: 'piutang',
    status: 'belum lunas',
    date: '2024-05-22',
    dueDate: '2024-06-30',
    description: 'Jasa freelance penulisan artikel',
  },
];
